driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  enforce_idempotency: true
  multiple_converge: 2
  deprecations_as_errors: true
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: debian-11
    driver:
      image: debian:11
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: debian-12
    driver:
      image: debian:12
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: almalinux-8
    driver:
      image: almalinux:8
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install lsof which systemd-sysv initscripts wget net-tools

  - name: almalinux-9
    driver:
      image: almalinux:9
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install lsof which systemd-sysv initscripts wget net-tools

  - name: fedora-38
    driver:
      image: fedora:38
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install which systemd-sysv initscripts wget net-tools

  - name: ubuntu-20.04
    driver:
      image: ubuntu:20.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: ubuntu-22.04
    driver:
      image: ubuntu:22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

suites:
  - name: default
    run_list: test::default
  - name: create
    run_list: test::create
  - name: remove
    run_list: test::remove
