language: ruby
cache: bundler
dist: bionic

addons:
  apt:
    sources:
      - chef-current-focal
    packages:
      - chef-workstation

env:
  global:
    - CHEF_LICENSE=accept-no-persist

services: docker

env:
  matrix:
    - CHEF_VERSION=16 INSTANCE=default-ubuntu-2004
    - CHEF_VERSION=16 INSTANCE=default-centos-8
    - CHEF_VERSION=16 INSTANCE=create-ubuntu-2004
    - CHEF_VERSION=16 INSTANCE=create-centos-8
    - CHEF_VERSION=16 INSTANCE=remove-ubuntu-2004

before_script:
  - sudo systemctl start docker
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - chef gem install kitchen-dokken

script:
  - chef exec delivery local all
  - kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
        - chef exec delivery local all
      env: UNIT_AND_LINT=1
