name 'tcp_wrappers'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
description 'Installs tcp_wrappers and configures /etc/hosts.deny, and hosts.allow'
version '0.4.0'

supports 'ubuntu', '>= 20.04'
supports 'debian', '>= 11.0'
supports 'redhat', '>= 8.0'
supports 'almalinux', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'amazon', '>= 2.0'
supports 'fedora', '>= 36.0'

source_url 'https://github.com/thomasvincent/chef-tcp-wrappers'
issues_url 'https://github.com/thomasvincent/chef-tcp-wrappers/issues'
chef_version '>= 18.0'
