services:
  chef-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/chef/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: sleep infinity
    network_mode: bridge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true

  # Test Kitchen target containers can be added here
  # Example Ubuntu test target
  test-ubuntu:
    image: ubuntu:22.04
    command: sleep infinity
    networks:
      - chef-test
    depends_on:
      - chef-dev

  # Example Rocky Linux test target (CentOS 8 replacement)
  test-rocky:
    image: rockylinux:8
    command: sleep infinity
    networks:
      - chef-test
    depends_on:
      - chef-dev

networks:
  chef-test:
    driver: bridge