---
name: Cookbook CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-kitchen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Lint and unit tests in Docker
          - task: 'lint'
          - task: 'unit'
          # Integration tests across platforms
          - task: 'integration'
            os: 'ubuntu-2204'
            suite: 'default'
          - task: 'integration'
            os: 'debian-11'
            suite: 'default'
          - task: 'integration'
            os: 'almalinux-9'
            suite: 'default'
          - task: 'integration'
            os: 'ubuntu-2204'
            suite: 'create'
          - task: 'integration'
            os: 'ubuntu-2204'
            suite: 'remove'
      fail-fast: false
      max-parallel: 3

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Run linting in Docker
        if: matrix.task == 'lint'
        run: |
          docker run --rm -v $(pwd):/cookbook -w /cookbook chef/chefworkstation:latest bash -c "apt-get update && apt-get install -y ruby-dev build-essential && gem install cookstyle -v '7.32.1' && cookstyle --fail-level E"
      
      - name: Run ChefSpec unit tests in Docker
        if: matrix.task == 'unit'
        run: |
          docker run --rm -v $(pwd):/cookbook -w /cookbook chef/chefworkstation:latest bash -c "apt-get update && apt-get install -y ruby-dev build-essential && bundle install && bundle exec rspec"
      
      - name: Run Test Kitchen integration tests
        if: matrix.task == 'integration'
        run: |
          docker run --rm -v $(pwd):/cookbook -v /var/run/docker.sock:/var/run/docker.sock -w /cookbook chef/chefworkstation:latest bash -c "apt-get update && apt-get install -y ruby-dev build-essential && bundle install && bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} || bundle exec kitchen verify ${{ matrix.suite }}-${{ matrix.os }}"
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_YAML: kitchen.yml