---
name: PR Assignment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to creator
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add reviewer
        uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: thomasvincent
          reviewers: thomasvincent